version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: yduqs-portais-desafio-user
      POSTGRES_PASSWORD: yduqs-portais-desafio-password
      POSTGRES_DB: yduqs-portais-desafio-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
